server:
  port: 8421
spring:
  application:
    name: orderRpc-service
  cloud:
    nacos:
      discovery:
        server-addr: 121.196.105.239:8848
        username: nacos
        password: nacos
        #metadata:
          #version: v1
          #其他自定义元数据: xxx
        #namespace: 95d7cfcb-6706-4be9-960d-dd0c89da171b
        #group: pay
        #cluster-name: NJ
  profiles:
    active: db

#ribbon的超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
#  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
#  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
#  OkToRetryOnAllOperations: false  #是否所有操作都重试
#  MaxTotalConnections: 500  #最大连接数
#  MaxConnectionsPerHost: 500  # 每个host最大连接数
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule  #负载均衡策略


# 对具体的服务设置超时时间
#application-name:
#  ribbon.ReadTimeout: 8000
#  ribbon.ConnectTimeout: 6000


# mybatis配置文件和 mapper映射文件
mybatis:
  #如果Mapper.xml与Mapper.class在同一个包下且同名，spring扫描Mapper.class的同时会自动扫描同名的Mapper.xml并装配到Mapper.class。
  #如果Mapper.xml与Mapper.class不在同一个包下或者不同名，就必须使用配置mapperLocations指定mapper.xml的位置。
  mapper‐locations: classpath:mybatis/mapper/*.xml   # 指定Mapper接口对应的XML文件的位置
  # mybatis配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  #type-aliases-package: com.wmk.pojo  #不影响运行，但是会变红


#日志
logging:
  pattern:
    console: '%logger{50} == %msg%n'
  level:
    com.wmk.mapper: debug
