server:
  port: 8420

spring:
  datasource:
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
      url: jdbc:mysql://121.196.105.239:3306/product_table?serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        server-addr: 121.196.105.239:8848
        username: nacos
        password: nacos
        #metadata:
        #version: v1
        namespace: 84eeca25-3230-4e13-9e53-b29132cd40cd
        #group: pay
        #cluster-name: NJ

seata:
  tx-service-group: my_test_tx_group

  config:
    type: nacos
    nacos:
      server-addr: 121.196.105.239:8848
      group: SEATA_GROUP
      namespace: 84eeca25-3230-4e13-9e53-b29132cd40cd

  registry:
    type: nacos
    nacos:
      server-addr: 121.196.105.239:8848
      group: SEATA_GROUP
      namespace: 84eeca25-3230-4e13-9e53-b29132cd40cd

  service:
    vgroup-mapping:
      my_test_tx_group: default  # 与nacos-config中一致
#    disable-global-transaction: false

#  client:
#    rm:
#      report-success-enable: false
#  enabled: true
#  enable-auto-data-source-proxy: true



#mybatis配置文件和mapper映射文件
mybatis:
  mapper‐locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  # type-aliases-package: com.wmk.pojo  #不影响运行，但是会变红
#日志
logging:
  pattern:
    console: '%logger{50} == %msg%n'
  level:
    com.wmk.mapper: debug