server:
  port: 7777

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 121.196.105.239:8848
        #namespace: 95d7cfcb-6706-4be9-960d-dd0c89da171b
    gateway:
      enabled: true  # 是否启用网关
      discovery:
        locator:
          enabled: false   # 能否根据微服务名称进行映射调用(生产不推荐，暴露了微服务)  http://localhost:7777/orderRpc-service/order/addOrderCount
#          lower-case-service-id: true
    sentinel:
      transport:
        dashboard: localhost:8080
#      datasource:
#        flow:
#          nacos:
#            server-addr: 121.196.105.239:8848
#            username: naocs
#            password: naocs
#            #namespace: 95d7cfcb-6706-4be9-960d-dd0c89da171b
#            groupId: SENTINEL_GROUP
#            dataId: ${spring.application.name}-gw-api-group
#            rule-type: flow
  profiles:
    active: gateway    # 可以加载多个，用逗号隔开
