server:
  port: 7777

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 121.196.105.239:8848
        namespace: 84eeca25-3230-4e13-9e53-b29132cd40cd
    gateway:
      enabled: true  # 是否启用网关
      discovery:
        locator:
          enabled: false   # 能否根据微服务名称进行映射调用(生产不推荐，暴露了微服务)  http://localhost:7777/orderRpc-service/order/addOrderCount
#          lower-case-service-id: true
  profiles:
    active: gateway    # 可以加载多个，用逗号隔开
