spring:
  rabbitmq:
    host: 121.196.105.239
    port: 5672
    username: wmk
    password: wmk
    virtual-host: wmkHost
    listener:
      simple:
        acknowledge-mode: manual  # 手动应答
        prefetch: 2500
server:
  port: 8082