server:
  port: 8400

spring:
  application:
    name: sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 121.196.105.239:8848 #Nacos服务注册中心地址
        #namespace: 95d7cfcb-6706-4be9-960d-dd0c89da171b
    sentinel:
      transport:
        #dashboard: 121.196.105.239:6001   #配置Sentinel dashboard地址
        dashboard: localhost:8080   #配置Sentinel dashboard地址
        # port: 8719   # 在应用对应的机器上启动一个Http Server，该Server会与 Sentinel控制台做交互，不配默认8719
#      filter:
#        enabled: true
      datasource:
        flow:
          nacos:
            server-addr: 121.196.105.239:8848
            username: naocs
            password: naocs
            #namespace: 95d7cfcb-6706-4be9-960d-dd0c89da171b
            groupId: SENTINEL_GROUP
            dataId: ${spring.application.name}-flow-rules
            rule-type: flow


management:
  endpoints:
    web:
      exposure:
        include: '*'

#feign:
#  sentinel:
#    enabled: true # 激活Sentinel对Feign的支持

# 开启@SentinelRestTemplate注解 整合ribbon
#resttemplate:
#  sentinel:
#    enabled: true
