server:
  port: 8420
spring:
  application:
    name: productRpc-service
  cloud:
    nacos:
      discovery:
        server-addr: 121.196.105.239:8848
        username: nacos
        password: nacos
        #metadata:
          #version: v1
        #namespace: 95d7cfcb-6706-4be9-960d-dd0c89da171b
        #group: pay
        cluster-name: NJ
  profiles:
    active: db

#mybatis配置文件和mapper映射文件
mybatis:
  mapper‐locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  # type-aliases-package: com.wmk.pojo  #不影响运行，但是会变红
#日志
logging:
  pattern:
    console: '%logger{50} == %msg%n'
  level:
    com.wmk.mapper: debug